# Generated by Django 5.0.6 on 2024-09-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category2',
            new_name='Category',
        ),
    ]
