# Generated by Django 5.0.7 on 2024-09-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0003_category_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo_url',
            field=models.URLField(max_length=255, verbose_name='Ссылка на фото'),
        ),
    ]
