# Generated by Django 5.0.7 on 2024-12-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
